- name: Create Jenkins Jobs
  hosts: localhost
  connection: local
  tasks:
  - name: Create Jenkins Jobs
    community.general.jenkins_job:
      config: "{{ lookup('file', 'test.xml') }}"
      name: test-create-from-ansible
      password: admin123
      url: http://34.201.5.159:8080