- name: Single Branch Pipelines
  ansible.builtin.include_tasks:
    file: sjobs.yml
  loop: "{{sjobs}}"

- name: multi Branch Pipelines
  ansible.builtin.include_tasks:
    file: mjobs.yml
  loop: "{{mjobs}}"