sjobs:
  - { git_repo_url: https://github.com/pavanbairu/roboshop-terraform.git, job_name: roboshop-terraform }
  - { git_repo_url: https://github.com/pavanbairu/roboshop-ansible.git, job_name: roboshop-ansible }
  - { git_repo_url: https://github.com/pavanbairu/aws-ssm-parameter-store.git, job_name: aws-ssm-parameter-store }

mjobs:
  - { git_repo_url: https://github.com/pavanbairu/cart.git, job_name: cart }
  - { git_repo_url: https://github.com/pavanbairu/catalogue.git, job_name: catalogue }
  - { git_repo_url: https://github.com/pavanbairu/user.git, job_name: user }
  - { git_repo_url: https://github.com/pavanbairu/shipping.git, job_name: shipping }
  - { git_repo_url: https://github.com/pavanbairu/payment.git, job_name: payment }
  - { git_repo_url: https://github.com/pavanbairu/dispatch.git, job_name: dispatch }